<a href="https://colab.research.google.com/github/Vibrant-Oracle/Python_Examples/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
import numpy as np # creating alice to make it use easily

In [ ]:
array1= np.array([10,20,30])
type(array1)


numpy.ndarray

In [ ]:
arr2d= np.array([[1,2,3],[4,5,6]])
arr2d #print the single line statement just above the call
# type(arr2d)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d = np.array([
    [1,2,3],
    [2,3,4],
    [7,8,9.0]
])
arr3d

array([[1., 2., 3.],
       [2., 3., 4.],
       [7., 8., 9.]])

sab float me convert ho gye it contain same data type it is homogeneous data types , not stored in continous memory locations, it is part of numpy


In [ ]:
#Attributes in numpy array
#1.ndim shows dimensions of array
#2.shape shows how many rows and coloumns are there
#3.size  shows no. of elements
#4.dtype shows data type _ <U1> unicode 1 it has all like img,audio,vedio

In [ ]:
arr3d.ndim

2

In [ ]:
arr3d.shape

(3, 3)

In [ ]:
arr3d.size

9

In [ ]:
arrstr= np.array(["a","b","c"])
arrstr.dtype

dtype('<U1')

#array create

In [17]:
arr1= np.array([[1,2],[3,4]], dtype=float)
arr1

array([[1., 2.],
       [3., 4.]])

In [18]:
arr1= np.array([[1,2],[3,4]], dtype=str )
arr1

array([['1', '2'],
       ['3', '4']], dtype='<U1')

Zero array

In [19]:
arr2= np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
arr2= np.zeros((3,4), dtype=int)
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
arr3= np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr3= np.ones((3,4), dtype=int)
arr3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
arr4 =np.full((3,3), 9 )
arr4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [24]:
arr4 =np.full((3,3), "c" )
arr4

array([['c', 'c', 'c'],
       ['c', 'c', 'c'],
       ['c', 'c', 'c']], dtype='<U1')

In [26]:
arr5=np.arange(6) #arange is like range in python
arr5

array([0, 1, 2, 3, 4, 5])

In [27]:
arr5 = np.arange(3,12)
arr5

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
arr5 = np.arange(3,12, 4) # start,stop,steps
arr5

array([ 3,  7, 11])